ci: add release workflow
OpenRailAssociation/osrd-images pull request #6
Opened 2024-09-24 13:41 UTC by younesschrifi

2024-09-24 14:10 UTC, Khoyo commented on .github/workflows/release.yml
> +          docker build -t ghcr.io/${{ github.repository_owner }}/osrd-stable/osrd-images
You need to tag with the release number here (eg. `ghcr.io/${{ github.repository_owner }}/osrd-stable/osrd-images:v0.3.2`)

2024-09-24 14:10 UTC, Khoyo commented on .github/workflows/release.yml
> +          docker push ghcr.io/${{ github.repository_owner }}/osrd-stable/osrd-images
Ditto

2024-09-24 15:56 UTC, ghost commented on .github/workflows/release.yml
> +        uses: docker/setup-buildx-action@v2
Use latest version (v3)

2024-09-24 15:56 UTC, ElysaSrc commented on .github/workflows/release.yml
> +        uses: actions/checkout@v3
Use latest version (v4)

2024-09-24 15:57 UTC, ElysaSrc commented on .github/workflows/release.yml
> +        uses: docker/login-action@v2
Use latest version (v3)

2024-09-24 15:58 UTC, ElysaSrc requested changes
LGTM overall, we should just use latest version on each action.

2024-09-24 16:04 UTC, flomonster approved these changes

2024-09-25 04:48 UTC, Khoyo approved these changes

2024-09-25 06:29 UTC, ElysaSrc approved these changes

2024-09-25 06:29 UTC, merged